/*This file was generated by NativeWind. Do not edit!*/
const {
  NativeWindStyleSheet: _NativeWindStyleSheet
} = require("nativewind");
_NativeWindStyleSheet.create({
  styles: {
    "sanity-app-no-js__root": {
      "position": "absolute",
      "top": 0,
      "right": 0,
      "left": 0,
      "bottom": 0,
      "backgroundColor": "#fff"
    },
    "sanity-app-no-js__content": {
      "position": "absolute",
      "top": "50%",
      "left": "50%",
      "textAlign": "center",
      "fontFamily": "helvetica"
    },
    "html": {
      "height": "100%"
    },
    "body": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "#sanity": {
      "height": "100%"
    }
  }
});